version: "3"
services:
   yarn:
      image: node:14-buster
      container_name: yarn
      working_dir: /opt/project
      volumes:
         - ./:/opt/project
      entrypoint: yarn
   app:
      extends:
         file: docker-compose.root.yml
         service: app
      container_name: app
      volumes:
         - "./packages/app:/opt/project/packages/app"
         - "./packages/mylib:/opt/project/packages/mylib"
      entrypoint: yarn workspace @travbern/app
